name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Calculate new tag
        id: newtag
        run: |
          LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null)
          if [ "$?" -ne 0 ]; then
            echo "NEW_TAG=1.0.0" >> $GITHUB_ENV
          else
            echo "NEW_TAG=$(echo $LAST_TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')" >> $GITHUB_ENV
          fi

      - name: Create new tag
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.RN_BOILERPLATE}}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.NEW_TAG }}',
              sha: context.sha
            })

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RN_BOILERPLATE }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: Release ${{ env.NEW_TAG }}
          draft: false
          prerelease: false
