name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calculate new tag from package.json version
        id: newtag
        run: |
          echo ::set-output name=NEW_TAG::$(node -e "console.log(require('./package.json').version)")

      - name: Create new tag
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.RN_BOILERPLATE}}
          script: |
            const newTag = `refs/tags/${{ steps.newtag.outputs.NEW_TAG }}`;
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: newTag,
              sha: context.sha
            });

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RN_BOILERPLATE }}
        with:
          tag_name: ${{ steps.newtag.outputs.NEW_TAG }}
          release_name: Release ${{ steps.newtag.outputs.NEW_TAG }}
          draft: false
          prerelease: false
          body: |
            Release ${{ steps.newtag.outputs.NEW_TAG }}
